### ISSUE TITLE
Kaggle

### ISSUE THREAD

**Issue by junxnone** [junxnone/Kaggle#1]
# TO-DO

- [ ] Inclass - 课业比赛
- [ ] Getting Started - 入门比赛
  - [ ] Digit Recognizer #3
- [ ] Playground - 训练场
- [ ] Research - 研究型
- [ ] Recruitment - 研究型
- [ ] Featured - 推荐比赛,大型组织比赛
- [ ] Masters - 限量邀请赛 
- [ ] Analytics - 选择最优评估标准来排名的比赛

# Reference
- [ ] [Kaggle](https://www.kaggle.com/)
- [ ] [Kaggle 项目实战（教程）](https://github.com/apachecn/kaggle)

# Projects
- [ ] [Facial Expression](https://www.kaggle.com/search?q=Facial+Expression+in%3Acompetitions)

# Steps
- 问题定义
- 模型选择
- 优化方向
  - 数据增强
    - Mixup
    - Copying & Pasting
  - Loss 函数
  - Learning Rate Policy
